name: Minespades
version: '${project.version}'
main: me.nologic.minespades.Minespades
api-version: 1.19
authors: [ NoLogic ]
description: Modern battlegrounds plugin.

depend:
  - ProtocolLib

softdepend:
  - PlaceholderAPI
  - AuthMe