name: Minespades
version: '${project.version}'
main: me.nologic.minespades.Minespades
api-version: 1.18
authors: [ NoLogic ]
description: "Clever and customizable TDM/CTF PvP battlegrounds for your sever."

depend:
  - ProtocolLib

softdepend:
  - PlaceholderAPI
  - AuthMe
  - Vault
  - Citizens