name: Minespades
version: '${project.version}'
main: me.nologic.minespades.Minespades
api-version: 1.19
authors: [ NoLogic ]
description: An exciting pvp-minigame with many unique features and a modern implementation.

depend:
  - ProtocolLib

softdepend:
  - PlaceholderAPI
  - AuthMe