name: Minespades
version: '${project.version}'
main: me.nologic.minespades.Minespades
api-version: 1.18
authors: [ NoLogic ]
description: "Modern and very customizable TDM/CTF/1CTF PvP arenas with some unique features."

depend:
  - ProtocolLib

softdepend:
  - PlaceholderAPI
  - AuthMe
  - Vault
  - Citizens