name: Minespades
version: '${project.version}'
main: me.nologic.minespades.Minespades
api-version: 1.18
authors: [ NoLogic ]
description: "TDM/CTF PvP minigame with some unique features and modern implementation."

depend:
  - ProtocolLib

softdepend:
  - PlaceholderAPI
  - AuthMe