name: Minespades
version: '${project.version}'
main: me.nologic.minespades.Minespades
api-version: 1.18
authors: [ NoLogic ]
description: "TDM/CTF PvP-minigame with a bunch of modern and unique features."

depend:
  - ProtocolLib

softdepend:
  - PlaceholderAPI
  - AuthMe